### ISSUE TITLE
TypeError: Cannot read property 'allowedOrigins' of undefined

### ISSUE THREAD

**Issue by Bachstelze** [Ostico/docker_matecat#19]
With 'docker-compose up' this error occurs:
'''
docker_bionic_matecat | const allowedOrigins = config.cors.allowedOrigins;
docker_bionic_matecat |                                    ^
docker_bionic_matecat | 
docker_bionic_matecat | TypeError: Cannot read property 'allowedOrigins' of undefined
docker_bionic_matecat |     at Object.<anonymous> (/var/www/matecat/nodejs/server.js:34:36)
docker_bionic_matecat |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
docker_bionic_matecat |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
docker_bionic_matecat |     at Module.load (internal/modules/cjs/loader.js:928:32)
docker_bionic_matecat |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
docker_bionic_matecat |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
docker_bionic_matecat |     at internal/main/run_main_module.js:17:47
'''
Do i have to configure the allowed origins?

**Comment by Ostico** [comment]
Hi @Bachstelze 

thy with this nodejs config ( `/<path_to_matecat_installation_dir>/matecat/nodejs/config.ini` ):

```
[server]
address = 0.0.0.0
port = 7788
path = /channel/updates

[queue]
name = /topic/matecat_sse_notifications
port = 61613
host = amq

[log]
file = log/server.log
level = debug

[cors]
allowedOrigins[] = *
```

**Comment by Bachstelze** [comment]
Hey @Ostico 
now i get this error: `SSL_ERROR_RX_RECORD_TOO_LONG`
also with this removed block:
```
    ## Remove this environment block if you don't need it ##
    environment:
      XDEBUG_CONFIG: 192.168.1.1
      FILTERS_ADDRESS: http://filters:8732/
      SMTP_HOST: 10.30.1.225
      SMTP_PORT: 2637
    ## Remove this environment block if you don't need it ##
```
